### PR TITLE
Added Star Jailbreak (iOS 4.0.1 and earlier)

### PR DESCRIPTION
**Pull request by JMK19**
My WYSIWYG editor "fixed" some of the code (or what it thinks is "fixing"), so, you're welcome.... i guess?

### CODE REVIEW

**Comment by The-Hacker894** [comment]
> why would the guide need .bak files?

The `.bak` files don't effect the guide. I've reviewed the changes and it looks pretty solid. I'll wait on @iraizo 's opinion before merging.

**Comment by iraizo** [comment]
they dont effect the guide they are still useless and just take space in the repo, if they are removed its a okay

**Comment by The-Hacker894** [comment]
Well then I'll remove the .bak files

**Comment by JMK19** [comment]
You can remove the .bak files, sorry. My editor does it automatically.

**Pull request merged**
